//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sku_to_smv.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size MainWndSize {
            get {
                return ((global::System.Drawing.Size)(this["MainWndSize"]));
            }
            set {
                this["MainWndSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainWndMaximized {
            get {
                return ((bool)(this["MainWndMaximized"]));
            }
            set {
                this["MainWndMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autosave {
            get {
                return ((bool)(this["Autosave"]));
            }
            set {
                this["Autosave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string AutosavePeriod {
            get {
                return ((string)(this["AutosavePeriod"]));
            }
            set {
                this["AutosavePeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public string SimulationPeriod {
            get {
                return ((string)(this["SimulationPeriod"]));
            }
            set {
                this["SimulationPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogSimulation {
            get {
                return ((bool)(this["LogSimulation"]));
            }
            set {
                this["LogSimulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 12pt")]
        public global::System.Drawing.Font TextFieldTextFont {
            get {
                return ((global::System.Drawing.Font)(this["TextFieldTextFont"]));
            }
            set {
                this["TextFieldTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TextFieldTextColor {
            get {
                return ((global::System.Drawing.Color)(this["TextFieldTextColor"]));
            }
            set {
                this["TextFieldTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color TextFieldCommentColor {
            get {
                return ((global::System.Drawing.Color)(this["TextFieldCommentColor"]));
            }
            set {
                this["TextFieldCommentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color TextFieldSignalColor {
            get {
                return ((global::System.Drawing.Color)(this["TextFieldSignalColor"]));
            }
            set {
                this["TextFieldSignalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextFieldHighLightning {
            get {
                return ((bool)(this["TextFieldHighLightning"]));
            }
            set {
                this["TextFieldHighLightning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int TextFieldHighLightPeriod {
            get {
                return ((int)(this["TextFieldHighLightPeriod"]));
            }
            set {
                this["TextFieldHighLightPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 14.25pt")]
        public global::System.Drawing.Font GrafFieldTextFont {
            get {
                return ((global::System.Drawing.Font)(this["GrafFieldTextFont"]));
            }
            set {
                this["GrafFieldTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color GrafFieldTextColor {
            get {
                return ((global::System.Drawing.Color)(this["GrafFieldTextColor"]));
            }
            set {
                this["GrafFieldTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color GrafFieldLocalSignalColor {
            get {
                return ((global::System.Drawing.Color)(this["GrafFieldLocalSignalColor"]));
            }
            set {
                this["GrafFieldLocalSignalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color GrafFieldInputSignalColor {
            get {
                return ((global::System.Drawing.Color)(this["GrafFieldInputSignalColor"]));
            }
            set {
                this["GrafFieldInputSignalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color GrafFieldSygnalSelectionColor {
            get {
                return ((global::System.Drawing.Color)(this["GrafFieldSygnalSelectionColor"]));
            }
            set {
                this["GrafFieldSygnalSelectionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ToolsPanelLocation {
            get {
                return ((int)(this["ToolsPanelLocation"]));
            }
            set {
                this["ToolsPanelLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 128")]
        public global::System.Drawing.Color GrafFieldSignalActiveColor {
            get {
                return ((global::System.Drawing.Color)(this["GrafFieldSignalActiveColor"]));
            }
            set {
                this["GrafFieldSignalActiveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color GrafFieldOutputSignalColor {
            get {
                return ((global::System.Drawing.Color)(this["GrafFieldOutputSignalColor"]));
            }
            set {
                this["GrafFieldOutputSignalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 192")]
        public global::System.Drawing.Color TextFieldOptionColor {
            get {
                return ((global::System.Drawing.Color)(this["TextFieldOptionColor"]));
            }
            set {
                this["TextFieldOptionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LogFormat {
            get {
                return ((int)(this["LogFormat"]));
            }
            set {
                this["LogFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainWndFullScreen {
            get {
                return ((bool)(this["MainWndFullScreen"]));
            }
            set {
                this["MainWndFullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextFieldEnableHighLight {
            get {
                return ((bool)(this["TextFieldEnableHighLight"]));
            }
            set {
                this["TextFieldEnableHighLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int StateDiametr {
            get {
                return ((int)(this["StateDiametr"]));
            }
            set {
                this["StateDiametr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int StateCentre {
            get {
                return ((int)(this["StateCentre"]));
            }
            set {
                this["StateCentre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int OffsetStateX {
            get {
                return ((int)(this["OffsetStateX"]));
            }
            set {
                this["OffsetStateX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public int OffsetStateY {
            get {
                return ((int)(this["OffsetStateY"]));
            }
            set {
                this["OffsetStateY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman, 14pt")]
        public global::System.Drawing.Font StateNameText {
            get {
                return ((global::System.Drawing.Font)(this["StateNameText"]));
            }
            set {
                this["StateNameText"] = value;
            }
        }
    }
}
